# Generated by Django 4.2.29 on 2026-03-30 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0121_alter_estimate_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspaceuserlink',
            name='project',
        ),
    ]
